# Generated by Django 4.2.9 on 2024-02-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sentEmails', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AurisonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=35)),
                ('submittedPass', models.BooleanField(default=False)),
                ('openedEmail', models.BooleanField(default=False)),
                ('clickedLink', models.BooleanField(default=False)),
                ('sentEmail', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=4)),
                ('campaign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.campaign')),
            ],
        ),
    ]
