version: '1'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations core && 
                python manage.py migrate &&
                python manage.py collectstatic --noinput &&
                gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - celery
      - postgres

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: phish
      POSTGRES_USER: aurison
      POSTGRES_PASSWORD: aurisonsayshi!
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      
  rabbitmq:
    ports:
      - '5672:5672'
volumes:
  postgres:
    driver: local
