version: '1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: phish
      POSTGRES_USER: aurison
      POSTGRES_PASSWORD: aurisonsayshi!
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data


  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    container_name: aurisonPhish
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  
      
      
volumes:
  postgres:
    driver: local
