# Generated by Django 4.2.9 on 2024-02-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenID', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=35)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailID', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=35)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.campaign')),
            ],
        ),
    ]
