# Generated by Django 4.2.9 on 2024-02-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tokenID',
            field=models.CharField(max_length=30),
        ),
    ]
